#!/usr/bin/env python3
"""Phase 0 recon: connect to the WHOOP 5.0 band and dump its full GATT map.

Enumerates every service, characteristic, and descriptor with properties, then writes
docs/gatt_map_5.0.md. Structural only — no writes to the band, no reading of biometric data.
The band's device address is personal and is redacted from the output file.

Run with the phone's WHOOP app closed or the phone in airplane mode (one BLE connection at a time):
    python recon/enumerate.py                 # auto-match a device whose name contains "whoop"
    python recon/enumerate.py --name Aura      # match a different advertised name
    python recon/enumerate.py --address <id>   # skip scanning, connect straight to an address
"""
import argparse
import asyncio
from pathlib import Path

from bleak import BleakClient, BleakScanner

OUT = Path(__file__).resolve().parent.parent / "docs" / "gatt_map_5.0.md"


async def find_device(name, address, timeout):
    """Return a BLEDevice to connect to, or None if nothing matched."""
    if address:
        dev = await BleakScanner.find_device_by_address(address, timeout=timeout)
        if dev is None:
            print(f"No device found at address {address}.")
        return dev

    print(f"Scanning {timeout:.0f}s for a device named like '{name}'...")
    devices = await BleakScanner.discover(timeout=timeout)
    matches = [d for d in devices if d.name and name.lower() in d.name.lower()]
    if not matches:
        # Nothing matched — list what we saw so the user can re-run with --name/--address.
        print(f"No device matched '{name}'. Nearby devices:")
        for d in devices:
            print(f"  {d.address}  {d.name or '(no name)'}")
        return None
    if len(matches) > 1:
        print("Multiple matches; using the first. Others:")
        for d in matches[1:]:
            print(f"  {d.address}  {d.name}")
    return matches[0]


def render(client):
    """Build the markdown GATT map. Device address and serial are deliberately omitted (personal)."""
    lines = [
        "# WHOOP 5.0 GATT Map",
        "",
        "Generated by `recon/enumerate.py`. Device address redacted (personal).",
        "Band advertises as `WHOOP <serial>`; the serial is redacted (device-identifying).",
        "",
    ]
    for service in client.services:
        desc = getattr(service, "description", "") or ""
        lines.append(f"## Service `{service.uuid}`" + (f" — {desc}" if desc else ""))
        for char in service.characteristics:
            props = ", ".join(char.properties) or "none"
            cdesc = getattr(char, "description", "") or ""
            label = f" — {cdesc}" if cdesc else ""
            lines.append(f"- Characteristic `{char.uuid}` [{props}]{label}")
            for d in char.descriptors:
                lines.append(f"  - Descriptor `{d.uuid}`")
        lines.append("")
    return "\n".join(lines)


async def main():
    ap = argparse.ArgumentParser(description="Enumerate the WHOOP 5.0's GATT services.")
    ap.add_argument("--name", default="whoop", help="advertised-name substring to match")
    ap.add_argument("--address", help="connect straight to this address, skip scanning")
    ap.add_argument("--timeout", type=float, default=15.0, help="scan/connect timeout in seconds")
    args = ap.parse_args()

    device = await find_device(args.name, args.address, args.timeout)
    if device is None:
        raise SystemExit(1)

    # Address goes to the console for your own use, never into the committed map.
    print(f"Connecting to {device.name or '(no name)'} at {device.address} ...")
    async with BleakClient(device, timeout=args.timeout) as client:
        print("Connected. Enumerating GATT...")
        OUT.write_text(render(client))
        n_services = sum(1 for _ in client.services)
        print(f"Wrote {OUT} ({n_services} services).")


if __name__ == "__main__":
    asyncio.run(main())
